### ISSUE TITLE
No Notification on IOS Screen from Pushover

### ISSUE THREAD

**Issue by sabernaeeni** [joshuajung/116117bot#1]
Hey Joshua,

your bot works perfeclty fine! I only have one issue. I don't get any notifications on the IOS Screen when I get a Pushover message. The message appears in the pushover app but doesn't on the home screen. Do you have any idea what the problem is?

Greetings

**Comment by joshuajung** [comment]
Hey! The pushover API supports multiple priorities, see https://pushover.net/api. You can always change them in the code to adjust it to your own liking. Right now, the only message pushed with high priority is if a free appointment has been identified. Hope this helps.
