### ISSUE TITLE
merging of qualifications results into wrong data

### ISSUE THREAD

**Issue by not-a-feature** [joshuajung/116117bot#16]
As the new vaccination recommendation is here, it is no longer possible to get the status of BioNTech (L920), Moderna (L921) and AstraZeneca (L922) separately.

The new vaccine list merges the three together:
```json
[{
    "qualification": "L920",
    "name": "Comirnaty (BioNTech)",
     "interval": 21,
    "age": "16-17"
 },{
    "qualification": "L921",
    "name": "mRNA-1273 (Moderna)",
    "tssname": "Moderna, BioNTech, AstraZeneca",
    "interval": 28,
    "age": "18+"
}]
```

The `/rest/suche/termincheck?plz=XXXXX&leistungsmerkmale=LXXX` API is returning for L921/L922 now coupled values. 
They introduced the vaccination change today (07.03.2021) at around 14:40 and coupled the values today at 19:40.

![grafik](https://user-images.githubusercontent.com/25013642/110256031-f4929080-7f96-11eb-8605-f42c1a2e7fa8.png)

**Comment by joshuajung** [comment]
Thanks for alerting me to this! Impfterminmonitor will be updated in a while. I think this repo doesn't need any changes, so I'll close the issue for now. Please feel free to reopen if otherwise.
