### ISSUE TITLE
URL format has changed

### ISSUE THREAD

**Issue by FloRinke** [joshuajung/116117bot#7]
It seems the URL format has changed, so 116117bot doesn't recognize them anymore.

At least for me, current URLs are:
https://000-iz.impfterminservice.de/impftermine/service/12345
https://000-iz.impfterminservice.de/impftermine/suche/XXXX-XXXX-XXXX/123456
(placeholders 000 for numeric id, 12345 for zip code, XXXX-XXXX-XXXX for Vermittlungscode)

**Comment by joshuajung** [comment]
Thanks for reporting this! The current `main` branch should now support the latest versions again.

> https://000-iz.impfterminservice.de/impftermine/suche/XXXX-XXXX-XXXX/123456

This one I could reproduce.

> https://000-iz.impfterminservice.de/impftermine/service/12345

Are you sure this is the correct URL? When I select an IZ on impfterminservice.de, I still get redirected to a URL like this:
https://001-iz.impfterminservice.de/impftermine/service?plz=68163
(i.e. PLZ in the URL param, not in the path)

**Comment by FloRinke** [comment]
Thanks for your quick response, URL is accepted now

> > https://000-iz.impfterminservice.de/impftermine/service/12345
> 
> Are you sure this is the correct URL? When I select an IZ on impfterminservice.de, I still get redirected to a URL like this:
> https://001-iz.impfterminservice.de/impftermine/service?plz=68163
> (i.e. PLZ in the URL param, not in the path)

actually no, when looking up from start I also see the parameterized variant now. The one I reported was copied from the open tab I had been refreshing manually for some time, but I cannot say where this URL actually came from. As the existing URL works I don't think there is any action required at the moment.
